# Generated by Django 4.2 on 2023-04-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
